import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
type Props = {
  children: React.ReactNode;
};

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <head />
      <body>
        <header>
          <nav>
            <div>
              <Link href="/">Home</Link>{' '}
              <Link
                href="/unoptimized-jpeg"
                data-test-id="unoptimized-jpeg-link"
              >
                Unoptimized-JPEG
              </Link>{' '}
              <Link href="/optimized-jpg" data-test-id="optimized-jpg-link">
                Optimized-JPG
              </Link>{' '}
              <Link href="/optimized-avif" data-test-id="optimized-avif-link">
                Optimized-AVIF
              </Link>{' '}
              <Link
                href="/unoptimized-props-jpg"
                data-test-id="unoptimized-props-jpg-link"
              >
                Unoptimized-props-JPG
              </Link>{' '}
              <Link
                href="/unoptimized-props-avif"
                data-test-id="unoptimized-props-avif-link"
              >
                Unoptimized-props-AVIF
              </Link>
            </div>
          </nav>
        </header>
        {props.children}
      </body>
    </html>
  );
}
